import React from 'react';
import { Modal, Button, Row, Col, ListGroup } from 'react-bootstrap';

function SummaryModal({ show, onHide, scenario, buildingDamage, tsunamiDamagedBuildings, processedHomes }) {
  if (!scenario) return null;

  // Calculate statistics
  const damages = Object.values(buildingDamage);
  const collapsed = damages.filter(d => d >= 90).length;
  const severe = damages.filter(d => d >= 60 && d < 90).length;
  const moderate = damages.filter(d => d >= 30 && d < 60).length;
  const intact = damages.filter(d => d < 30).length;
  const total = processedHomes.length;
  const tsunamiDamaged = tsunamiDamagedBuildings.size;
  const hasTsunami = scenario.events.some(e => e.type === 'tsunami');
  const collapsedPercent = (collapsed / total) * 100;

  // Generate positives
  const generatePositives = () => {
    const positives = [];
    
    if (collapsedPercent < 15) {
      positives.push({
        icon: '🏗️',
        text: `${(100 - collapsedPercent).toFixed(0)}% of buildings avoided collapse — structural codes and retrofitting appear effective`
      });
    }
    
    if (hasTsunami && tsunamiDamaged < total * 0.5) {
      positives.push({
        icon: '🌊',
        text: `Tsunami damage limited to ${tsunamiDamaged} buildings — evacuation routes helped minimize exposure`
      });
    }
    
    positives.push({
      icon: '⏱️',
      text: 'Early warning systems provided advance notice for evacuations and preparation'
    });
    
    positives.push({
      icon: '📍',
      text: 'Real-time damage tracking enabled prioritized rescue operations'
    });
    
    return positives.slice(0, 4);
  };

  // Generate negatives
  const generateNegatives = () => {
    const negatives = [];
    
    if (collapsedPercent > 5) {
      negatives.push({
        icon: '🏚️',
        text: `${collapsed} buildings collapsed — review building codes for older structures and soft-story buildings`
      });
    }
    
    if (hasTsunami && tsunamiDamaged > 10) {
      negatives.push({
        icon: '🌊',
        text: `${tsunamiDamaged} structures in flood zone sustained water damage — consider updated inundation maps`
      });
    }
    
    if (severe > 20) {
      negatives.push({
        icon: '⚠️',
        text: `High severe damage count (${severe}) — liquefaction mitigation may need expansion in Marina fill areas`
      });
    }
    
    negatives.push({
      icon: '🛣️',
      text: 'Some evacuation routes were blocked by debris — need redundant route planning'
    });
    
    return negatives.slice(0, 4);
  };

  // Generate actions
  const generateActions = () => [
    {
      icon: '🔍',
      title: 'Search & Rescue Priority',
      description: `Deploy teams to ${collapsed} collapsed structures. Check adjacent buildings for structural integrity.`
    },
    {
      icon: '🏥',
      title: 'Medical Triage',
      description: `Establish aid stations near damage clusters. Estimate ${Math.round(collapsed * 2.5)} potential casualties requiring care.`
    },
    {
      icon: hasTsunami ? '💧' : '🔥',
      title: hasTsunami ? 'Water Damage Assessment' : 'Fire Watch',
      description: hasTsunami 
        ? 'Document flood damage for insurance/FEMA. Check for contamination and mold risk.'
        : 'Monitor for gas leaks and secondary fires. Coordinate with utilities.'
    },
    {
      icon: '📋',
      title: 'Damage Documentation',
      description: `Tag ${collapsed + severe} priority buildings with safety ratings. Coordinate rapid building inspection teams.`
    }
  ];

  // Export report
  const exportReport = () => {
    const report = `
POST-DISASTER SUMMARY REPORT
============================
Scenario: ${scenario.name}
Date: ${new Date().toLocaleString()}

DAMAGE STATISTICS
-----------------
Collapsed: ${collapsed}
Severe Damage: ${severe}
Moderate Damage: ${moderate}
Minor/Intact: ${intact}
Total Buildings Assessed: ${total}
Tsunami-Affected: ${tsunamiDamaged}

RECOMMENDED ACTIONS
-------------------
1. Deploy search & rescue to collapsed structures
2. Establish medical triage stations
3. Document damage for FEMA/insurance
4. Coordinate utility shut-offs
5. Begin rapid building inspections

Report generated by Quake Risk Assessment Dashboard
    `.trim();

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `disaster-report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <Modal show={show} onHide={onHide} size="lg" centered className="summary-modal">
      <Modal.Header 
        closeButton 
        closeVariant="white" 
        style={{ backgroundColor: '#1a1d24', borderBottom: '1px solid rgba(255,255,255,0.1)' }}
      >
        <Modal.Title style={{ color: '#f4f4f6' }}>
          <span className="me-2">📋</span>
          Post-Event Summary Report
        </Modal.Title>
      </Modal.Header>
      <Modal.Body style={{ backgroundColor: '#1a1d24' }}>
        <p style={{ color: '#9ca3af' }} className="mb-4">{scenario.name} - Response Complete</p>
        
        {/* Statistics */}
        <Row className="mb-4">
          <Col xs={3}>
            <div className="summary-stat" style={{ backgroundColor: '#0f1115', borderRadius: '12px', padding: '18px', textAlign: 'center' }}>
              <div style={{ fontSize: '2rem', fontWeight: 800, color: '#ef4444' }}>{collapsed}</div>
              <div style={{ fontSize: '0.75rem', color: '#9ca3af', textTransform: 'uppercase', marginTop: '8px' }}>Collapsed</div>
            </div>
          </Col>
          <Col xs={3}>
            <div className="summary-stat" style={{ backgroundColor: '#0f1115', borderRadius: '12px', padding: '18px', textAlign: 'center' }}>
              <div style={{ fontSize: '2rem', fontWeight: 800, color: '#f97316' }}>{severe}</div>
              <div style={{ fontSize: '0.75rem', color: '#9ca3af', textTransform: 'uppercase', marginTop: '8px' }}>Severe</div>
            </div>
          </Col>
          <Col xs={3}>
            <div className="summary-stat" style={{ backgroundColor: '#0f1115', borderRadius: '12px', padding: '18px', textAlign: 'center' }}>
              <div style={{ fontSize: '2rem', fontWeight: 800, color: '#f59e0b' }}>{moderate}</div>
              <div style={{ fontSize: '0.75rem', color: '#9ca3af', textTransform: 'uppercase', marginTop: '8px' }}>Moderate</div>
            </div>
          </Col>
          <Col xs={3}>
            <div className="summary-stat" style={{ backgroundColor: '#0f1115', borderRadius: '12px', padding: '18px', textAlign: 'center' }}>
              <div style={{ fontSize: '2rem', fontWeight: 800, color: '#10b981' }}>{intact}</div>
              <div style={{ fontSize: '0.75rem', color: '#9ca3af', textTransform: 'uppercase', marginTop: '8px' }}>Intact</div>
            </div>
          </Col>
        </Row>

        {/* What Worked Well */}
        <h6 className="mb-3" style={{ color: '#f4f4f6' }}>
          <span className="me-2">✅</span>
          What Worked Well
        </h6>
        <ListGroup className="mb-4">
          {generatePositives().map((item, idx) => (
            <ListGroup.Item 
              key={idx} 
              style={{ 
                backgroundColor: 'rgba(74,222,128,0.1)', 
                color: '#e2e8f0',
                borderLeft: '4px solid #10b981',
                borderTop: 'none',
                borderRight: 'none',
                borderBottom: '1px solid rgba(255,255,255,0.05)'
              }}
            >
              <span className="me-2">{item.icon}</span>
              {item.text}
            </ListGroup.Item>
          ))}
        </ListGroup>

        {/* Areas for Improvement */}
        <h6 className="mb-3" style={{ color: '#f4f4f6' }}>
          <span className="me-2">⚠️</span>
          Areas for Improvement
        </h6>
        <ListGroup className="mb-4">
          {generateNegatives().map((item, idx) => (
            <ListGroup.Item 
              key={idx} 
              style={{ 
                backgroundColor: 'rgba(248,113,113,0.1)', 
                color: '#e2e8f0',
                borderLeft: '4px solid #ef4444',
                borderTop: 'none',
                borderRight: 'none',
                borderBottom: '1px solid rgba(255,255,255,0.05)'
              }}
            >
              <span className="me-2">{item.icon}</span>
              {item.text}
            </ListGroup.Item>
          ))}
        </ListGroup>

        {/* Immediate Actions */}
        <h6 className="mb-3" style={{ color: '#f4f4f6' }}>
          <span className="me-2">🚨</span>
          Immediate Actions Required
        </h6>
        <Row>
          {generateActions().map((action, idx) => (
            <Col xs={6} key={idx} className="mb-3">
              <div style={{ 
                backgroundColor: 'rgba(255,255,255,0.05)', 
                padding: '16px', 
                borderRadius: '8px', 
                border: '1px solid rgba(255,255,255,0.1)',
                height: '100%'
              }}>
                <h6 className="mb-2" style={{ color: '#f4f4f6' }}>
                  <span className="me-2">{action.icon}</span>
                  {action.title}
                </h6>
                <p className="small mb-0" style={{ color: '#9ca3af' }}>{action.description}</p>
              </div>
            </Col>
          ))}
        </Row>
      </Modal.Body>
      <Modal.Footer style={{ backgroundColor: '#0f1115', borderTop: '1px solid rgba(255,255,255,0.1)' }}>
        <Button variant="outline-light" onClick={onHide}>
          Close
        </Button>
        <Button variant="primary" onClick={exportReport}>
          📄 Export Report
        </Button>
      </Modal.Footer>
    </Modal>
  );
}

export default SummaryModal;

